apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: client
          image: ghcr.io/httpcarlxs/ssip-demo-project:main
          args: ["-config", "/run/spiffe-helper/config/helper.conf"]
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: helper-config
              mountPath: /run/spiffe-helper/config
              readOnly: true
            - name: svid-certs
              mountPath: /certs
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: helper-config
          configMap:
            name: client
        - name: svid-certs
          emptyDir: {}
