name: Untrusted Pipeline

permissions: {}

on:
  workflow_dispatch: {}

jobs:
  call-trusted-pipeline:
    permissions:
      contents: read
      actions: read
      packages: write
      id-token: write
    uses: laerson/ssip-trusted-pipeline/.github/workflows/trusted-pipeline.yml@v1.0.0
    with:
      temp-registry: https://ssip-ufcg.privatedns.org/
      deployment: deployment.yml  # Esse arquivo está vazio
    secrets:
      intermediary-registry-username: ${{ secrets.TEMP_REP_USERNAME }}
      intermediary-registry-password: ${{ secrets.TEMP_REP_PASSWORD }}
  
